### ISSUE TITLE
Reproduce the result of hemolysis prediction

### ISSUE THREAD

**Issue by ZachKLYeh** [ChakradharG/PeptideBERT#2]
Hi there! I try to reproduce the result of hemolysis prediction
The only modification that I did is change the task in config.yaml to hemo
The result is 82.403, which is different from the paper(86.051)
Is there anything that I missed?

**Comment by ZachKLYeh** [comment]
epochs: 50                                                                                                                                                                                  
batch_size: 32
vocab_size: 25
task: hemo  # hemo, sol, nf
debug: false 

network:
  hidden_size: 480
  hidden_layers: 12
  attn_heads: 12
  dropout: 0.15

optim:
  lr: 1.0e-5

sch:
  name: lronplateau  # onecycle, lronplateau
  factor: 0.1
  patience: 4

**Comment by ChakradharG** [comment]
Hi there!

Thank you for reaching out and for your interest in reproducing the hemolysis prediction results.

The difference you're seeing in the results compared to the paper stems from the fact that the dataset is highly imbalanced. About 80% of the data points are labeled as `0` and, as such, the final test accuracy is highly sensitive to the splitting of the dataset. I would suggest running the `split_augment` script again to randomly split the dataset. This process might help mitigate the effect of an unfavorable split.

Closing the issue now, but please feel free to reopen it if you have any more questions or follow-ups.
