### ISSUE TITLE
How to compare with previous methodologies

### ISSUE THREAD

**Issue by ZachKLYeh** [ChakradharG/PeptideBERT#4]
Hello there! Thank you for your great work and sharing the implementation to the community!

I'm trying to reproduce your result and compare them with previous methodologies.
As the previous issue that I addressed, the code is using random split to generation train-validation-test set.
I wonder how you compare PeptideBERT with previous methodologies(e.g. HAPPENN, DSResSol, ...etc) if a random split is used?
Did you reproduce other methodologies and evaluate them on the specific split that split_augment.py generates?

If so, can you provide the code of your reproduction and the specific split that you are using?

**Comment by ChakradharG** [comment]
Unfortunately, the data-split used by the authors of previous methodologies is not part of the available dataset. We used the performance reported by the authors to compare against ours.
