### ISSUE TITLE
Request for Model Weights for PeptideBERT

### ISSUE THREAD

**Issue by Karththigan** [ChakradharG/PeptideBERT#7]
Thank you for making PeptideBERT accessible through this repository. I’m currently working on a project related to peptide property prediction and I believe using the pre-trained model from PeptideBERT would be very helpful.

I was wondering if you could kindly provide the model weights mentioned in the paper, or guide me on how to obtain them if they are available elsewhere? 

Thank you!

**Comment by ChakradharG** [comment]
Hello Karththigan, you can find the model weights in the [releases](https://github.com/ChakradharG/PeptideBERT/releases) section of the repository.

**Comment by Karththigan** [comment]
Thank you!
